In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

N = Samples
T = Sequence length
D = input features
M = Hidden units
K = Output units

In [15]:
N = 1
T = 10
D = 3
K = 2
X = np.random.randn(N, T, D)

In [16]:
X

array([[[-0.14657322,  0.77770267,  0.11097633],
        [ 0.33738772,  0.34694654, -1.14508662],
        [-0.29450723, -2.33523641, -0.56961754],
        [ 2.784122  ,  0.99996659, -0.29032831],
        [ 1.00146632, -0.99544986, -1.04642712],
        [ 0.06631387,  0.63955632,  0.13010682],
        [ 0.42189619, -0.65657712, -0.1305882 ],
        [-0.66876964, -0.79349386,  0.64552031],
        [ 1.19178334, -0.08163426, -3.05395062],
        [ 1.7097335 , -0.29768355, -0.86253699]]])

In [17]:
M = 5
i = Input(shape=(T, D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i, x)

In [18]:
Yhat = model.predict(X)
print(Yhat)

[[ 0.68342817 -0.4008093 ]]


In [20]:
model.summary()

Model: "functional_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 5)                 45        
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.layers[1].get_weights()

[array([[-0.36911026, -0.67589474,  0.32163042, -0.63739514, -0.5018126 ],
        [ 0.414028  , -0.10068291,  0.610146  , -0.31299323,  0.35350102],
        [ 0.70536476,  0.4794503 ,  0.5405498 , -0.512164  , -0.2511325 ]],
       dtype=float32),
 array([[ 0.22153366, -0.26038504, -0.17587325,  0.76630247,  0.5147538 ],
        [ 0.19866471,  0.9186663 ,  0.22509685,  0.19155541,  0.17094602],
        [-0.79938316,  0.03444219,  0.21258658, -0.08121508,  0.5549877 ],
        [-0.06326691, -0.20446283,  0.83531   ,  0.37161732, -0.3440206 ],
        [-0.518111  ,  0.21274543, -0.41888446,  0.48103207, -0.528625  ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [28]:
a, b, c  = model.layers[1].get_weights()
print(a.shape, b.shape, c.shape)

(3, 5) (5, 5) (5,)


In [29]:
Wx , Wh, bh = model.layers[1].get_weights()
Wo, bo = model.layers[2].get_weights()

In [32]:
h_last = np.zeros(M)
x = X[0]
Yhats = []

for t in range(T):
  h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
  y = h.dot(Wo) + bo
  Yhats.append(y)

  h_last = h
print(Yhats[-1])



[ 0.68342824 -0.40080939]
